import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Button from '@/components/Button'
import Input from '@/components/Input'
import Header from '@/components/Header'
import { useRouter } from 'next/router'

export default function Home() {

  const [name, setName] = useState('');

  const history = useRouter();

  useEffect(() => {
    const fethData = async () =>  {
      const data = await fetch('http://localhost:3000/api/user');
      const data_json = await data.json();
      setName(data_json.results.name)
    };
    fethData();
  })

  const redirectPage = () => {
    history.push(`/about/emilio`)
  }

  return (
    <>
      <Head>
        <title>Aulinha trybe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <div>
          {name && <p>Seja bem vindo {name}</p>}
          <Input />
          <Button redirectPage={ redirectPage }/>
        </div>
      </main>
    </>
  )
}
